2025-01-28 09:17:02,054:DEBUG:certbot._internal.main:certbot version: 3.1.0
2025-01-28 09:17:02,054:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-01-28 09:17:02,054:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/html', '--email', 'gusarov.as@fltrktv.ru', '--agree-tos', '--no-eff-email', '-d', 'fltrktv.ru']
2025-01-28 09:17:02,055:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-01-28 09:17:02,067:DEBUG:certbot._internal.log:Root logging level set at 30
2025-01-28 09:17:02,070:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2025-01-28 09:17:02,071:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7ff04cbc8da0>
Prep: True
2025-01-28 09:17:02,071:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7ff04cbc8da0> and installer None
2025-01-28 09:17:02,071:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2025-01-28 09:17:02,112:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2188860915', new_authzr_uri=None, terms_of_service=None), 07fbde8bedab8a49b720c3ac37096954, Meta(creation_dt=datetime.datetime(2025, 1, 24, 13, 38, 56, tzinfo=datetime.timezone.utc), creation_host='d4dcd3174b6e', register_to_eff=None))>
2025-01-28 09:17:02,114:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-01-28 09:17:02,117:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-01-28 09:17:02,692:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 828
2025-01-28 09:17:02,693:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 28 Jan 2025 09:17:05 GMT
Content-Type: application/json
Content-Length: 828
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "The same profile you're accustomed to"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "vxW6HAdWV-8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2025-01-28 09:17:02,693:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for fltrktv.ru
2025-01-28 09:17:02,695:DEBUG:acme.client:Requesting fresh nonce
2025-01-28 09:17:02,695:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-01-28 09:17:02,856:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-01-28 09:17:02,856:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 28 Jan 2025 09:17:05 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: Z6auUXuuPyeeaaq_v4uwhpdw35RXSJ86wtc9sZ80N82gfe1Av8k
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-01-28 09:17:02,856:DEBUG:acme.client:Storing nonce: Z6auUXuuPyeeaaq_v4uwhpdw35RXSJ86wtc9sZ80N82gfe1Av8k
2025-01-28 09:17:02,857:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "fltrktv.ru"\n    }\n  ]\n}'
2025-01-28 09:17:02,858:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE4ODg2MDkxNSIsICJub25jZSI6ICJaNmF1VVh1dVB5ZWVhYXFfdjR1d2hwZHczNVJYU0o4Nnd0YzlzWjgwTjgyZ2ZlMUF2OGsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "Mq-2UIde9u7TutWEMz4Oso58JUKrdbNuTnZoXyN0nDyYeF2ONk_3cxcWWzZw64ZVw45TTfKTC5Par4CldkIwzt9vn0m-Dr11vbOv_5QhRBZ4bvwhCBrhF9Qo3-dzhkuHdwu4AvBvInBFKNlPqfX2gqIAG8XlrFGuKYL6PIxKQtO_Ck696FrbPsqlmNrZtZNYRAxUAAEan7-VlVG-IxH1NSX1QFB4hzBW6qGOJpJI1p9aZ7KIa_bQFtHgZ6TnaM6MGk4Idj9c_DCaeaQ55WgLKsaN1EmQMJydDqVddoxF5O3DTMEZ41Ec9E0gydJm3SuAWx3mwI1h8yy0Sj3Jd-tdpw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImZsdHJrdHYucnUiCiAgICB9CiAgXQp9"
}
2025-01-28 09:17:03,177:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 344
2025-01-28 09:17:03,178:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Tue, 28 Jan 2025 09:17:05 GMT
Content-Type: application/json
Content-Length: 344
Connection: keep-alive
Boulder-Requester: 2188860915
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2188860915/348816745915
Replay-Nonce: KY2mD_Aj2epZJiZpQSZ3GfTPfP4F3k6OTNZeqI1wkh7I867WFYY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-02-04T09:17:05Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "fltrktv.ru"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2188860915/467419041945"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2188860915/348816745915"
}
2025-01-28 09:17:03,178:DEBUG:acme.client:Storing nonce: KY2mD_Aj2epZJiZpQSZ3GfTPfP4F3k6OTNZeqI1wkh7I867WFYY
2025-01-28 09:17:03,178:DEBUG:acme.client:JWS payload:
b''
2025-01-28 09:17:03,179:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2188860915/467419041945:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE4ODg2MDkxNSIsICJub25jZSI6ICJLWTJtRF9BajJlcFpKaVpwUVNaM0dmVFBmUDRGM2s2T1ROWmVxSTF3a2g3STg2N1dGWVkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxODg4NjA5MTUvNDY3NDE5MDQxOTQ1In0",
  "signature": "g-m9NSq02eFzmzKYMRkRb_mIOg3WmJ7evYT4vj_qdJcNxB8z40qOTNBAoaHnlzjNBhQ9E4hi-6VJjlMe5GAMuH7xWKYF7tw4p3pyNBXE2erJ0mLYHBtzwPW4mGuN4JUX3QGdt3BKaP8rCb2gFH8Dt-tWp13qYMAtzwWJFsgs7t9vqU1D5MngwAO0K2xXobDPTogpvuhVw-g4pi-0j2A-UD0DazxSmi7nHaptU06LWpFma9x8RKyRdaGScrXq3VIsP5steIv8eWiooj8uCimpVcpW3MuZtGy3Gf4wvfsiV7LCdTnsPpUqkAAAMrxnGmEj42jNihVnXuSuTEGuw4qmzQ",
  "payload": ""
}
2025-01-28 09:17:03,356:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2188860915/467419041945 HTTP/1.1" 200 818
2025-01-28 09:17:03,356:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 28 Jan 2025 09:17:06 GMT
Content-Type: application/json
Content-Length: 818
Connection: keep-alive
Boulder-Requester: 2188860915
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: KY2mD_AjkecSL8PDCORXUlvjtMu3I_9-9gPXkDKMj8CK40lFP94
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "fltrktv.ru"
  },
  "status": "pending",
  "expires": "2025-02-04T09:17:05Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/72ifmw",
      "status": "pending",
      "token": "IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/mvbGCw",
      "status": "pending",
      "token": "IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/KkhPZg",
      "status": "pending",
      "token": "IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ"
    }
  ]
}
2025-01-28 09:17:03,356:DEBUG:acme.client:Storing nonce: KY2mD_AjkecSL8PDCORXUlvjtMu3I_9-9gPXkDKMj8CK40lFP94
2025-01-28 09:17:03,357:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-01-28 09:17:03,357:INFO:certbot._internal.auth_handler:http-01 challenge for fltrktv.ru
2025-01-28 09:17:03,357:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/html for all unmatched domains.
2025-01-28 09:17:03,357:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/html/.well-known/acme-challenge
2025-01-28 09:17:03,358:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/html/.well-known/acme-challenge/IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ
2025-01-28 09:17:03,359:DEBUG:acme.client:JWS payload:
b'{}'
2025-01-28 09:17:03,359:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/KkhPZg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE4ODg2MDkxNSIsICJub25jZSI6ICJLWTJtRF9BamtlY1NMOFBEQ09SWFVsdmp0TXUzSV85LTlnUFhrREtNajhDSzQwbEZQOTQiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIxODg4NjA5MTUvNDY3NDE5MDQxOTQ1L0traFBaZyJ9",
  "signature": "Q8v5il7jdUSN2eDyorFNNLc84SjTGNrFaofP9AvwQ7BFXqQB2V14rJyUc5V_YPTcNI0BWil2YyggbLHSUOSKazFbxWpnpEhFGF5AOTnj53FyEQ0W3zO3itfQ_UcpxKD0S4aKiqlKqU0BXVV-KYIKqF84eP3QOOzd9Xv8O252rEW73mHnAUABiuUVIAT3o3qXn2t2_Kg-Uc7K-wr1l1yt_A7qKJGUxWffN9SMVW_CvSDa-_Rk7YK2FPFpXKY4W5E9E8p0lre3qpxTBJRORSNyHAn3snPOgb5ytxGhP4xDQBa45jTFyyNQTjFc9IBVzhFiTNL6251n_8GUIqv9iCvfsQ",
  "payload": "e30"
}
2025-01-28 09:17:03,528:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2188860915/467419041945/KkhPZg HTTP/1.1" 200 195
2025-01-28 09:17:03,528:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 28 Jan 2025 09:17:06 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2188860915
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2188860915/467419041945>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/KkhPZg
Replay-Nonce: Z6auUXuuzsQPcH0_zGKNj2mYflZx-Q9NeKholh4v-hKpxT0Pl-Y
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/KkhPZg",
  "status": "pending",
  "token": "IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ"
}
2025-01-28 09:17:03,529:DEBUG:acme.client:Storing nonce: Z6auUXuuzsQPcH0_zGKNj2mYflZx-Q9NeKholh4v-hKpxT0Pl-Y
2025-01-28 09:17:03,529:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-01-28 09:17:04,529:DEBUG:acme.client:JWS payload:
b''
2025-01-28 09:17:04,530:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2188860915/467419041945:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE4ODg2MDkxNSIsICJub25jZSI6ICJaNmF1VVh1dXpzUVBjSDBfekdLTmoybVlmbFp4LVE5TmVLaG9saDR2LWhLcHhUMFBsLVkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxODg4NjA5MTUvNDY3NDE5MDQxOTQ1In0",
  "signature": "beu-c_z1g85_QyaSV9HelS3nmlNbDMcmRD7cSJhzmGokRmkUhga6yyiWJGs_JtOabwpVrZP9pF-vycMdZuJF-UaKWXQlO98Tq0yb-sgWkUICBRxpS4LQEdEs-YyLhQUllLv0sj-CVTUd9yUlDpSSujLxWah5jGPlHAvGgErIXu4-9FfZQQzsZ18_51IogzZ4edAZJozVZ-tdseuWcXLJfE71NjK5xOEOYxnkjjGAefAwCA2Mw6PEeJbHS4pFeCjXab_N7BErrLEEsPgbg64n0A2GrACXsCf6iZvRfPpA3jLSTuCNtMVLx7oImSZxiYtsRWJ11RkFtWjagkid_iqcnQ",
  "payload": ""
}
2025-01-28 09:17:04,704:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2188860915/467419041945 HTTP/1.1" 200 1013
2025-01-28 09:17:04,704:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 28 Jan 2025 09:17:07 GMT
Content-Type: application/json
Content-Length: 1013
Connection: keep-alive
Boulder-Requester: 2188860915
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: Z6auUXuunk8oLVQAsWwDOW7T7ayKqhnDoaTB1Jwo9yuzUeRX0lc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "fltrktv.ru"
  },
  "status": "invalid",
  "expires": "2025-02-04T09:17:05Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2188860915/467419041945/KkhPZg",
      "status": "invalid",
      "validated": "2025-01-28T09:17:06Z",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "80.72.26.246: Invalid response from http://fltrktv.ru/.well-known/acme-challenge/IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ: 404",
        "status": 403
      },
      "token": "IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ",
      "validationRecord": [
        {
          "url": "http://fltrktv.ru/.well-known/acme-challenge/IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ",
          "hostname": "fltrktv.ru",
          "port": "80",
          "addressesResolved": [
            "80.72.26.246"
          ],
          "addressUsed": "80.72.26.246"
        }
      ]
    }
  ]
}
2025-01-28 09:17:04,704:DEBUG:acme.client:Storing nonce: Z6auUXuunk8oLVQAsWwDOW7T7ayKqhnDoaTB1Jwo9yuzUeRX0lc
2025-01-28 09:17:04,704:INFO:certbot._internal.auth_handler:Challenge failed for domain fltrktv.ru
2025-01-28 09:17:04,705:INFO:certbot._internal.auth_handler:http-01 challenge for fltrktv.ru
2025-01-28 09:17:04,705:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: fltrktv.ru
  Type:   unauthorized
  Detail: 80.72.26.246: Invalid response from http://fltrktv.ru/.well-known/acme-challenge/IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ: 404

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2025-01-28 09:17:04,705:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-01-28 09:17:04,706:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-01-28 09:17:04,706:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-01-28 09:17:04,706:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/html/.well-known/acme-challenge/IGhgPxpMYNowyXhFtT5Cyptly2rJv-2u9ZnphAHQbOQ
2025-01-28 09:17:04,706:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2025-01-28 09:17:04,706:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1579, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 518, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 429, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 497, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-01-28 09:17:04,708:ERROR:certbot._internal.log:Some challenges have failed.
